// GENERATED FROM tokens.json — DO NOT EDIT
package com.venbiasa.wailo.shared.theme

import androidx.compose.ui.graphics.Color

internal val LightBackground = Color(0xFFFFFFFF)
internal val LightOnBackground = Color(0xFF0A0A0A)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightSurfaceContainer = Color(0xFFFAFAFA)
internal val LightSurfaceVariant = Color(0xFFF5F5F5)
internal val LightOnSurface = Color(0xFF0A0A0A)
internal val LightOnSurfaceVariant = Color(0xFF525252)
internal val LightOnSurfaceDisabled = Color(0xFFA3A3A3)
internal val LightOutline = Color(0xFFD4D4D4)
internal val LightOutlineVariant = Color(0xFFE5E5E5)
internal val LightAccent = Color(0xFF0A0A0A)
internal val LightOnAccent = Color(0xFFFFFFFF)
internal val LightSuccess = Color(0xFF16A34A)
internal val LightOnSuccess = Color(0xFFFFFFFF)
internal val LightWarning = Color(0xFFF59E0B)
internal val LightOnWarning = Color(0xFF000000)
internal val LightError = Color(0xFFDC2626)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightInfo = Color(0xFF2563EB)
internal val LightOnInfo = Color(0xFFFFFFFF)
internal val LightScrim = Color(0x8F000000)

internal val DarkBackground = Color(0xFF000000)
internal val DarkOnBackground = Color(0xFFFAFAFA)
internal val DarkSurface = Color(0xFF0A0A0A)
internal val DarkSurfaceContainer = Color(0xFF171717)
internal val DarkSurfaceVariant = Color(0xFF262626)
internal val DarkOnSurface = Color(0xFFFAFAFA)
internal val DarkOnSurfaceVariant = Color(0xFFA3A3A3)
internal val DarkOnSurfaceDisabled = Color(0xFF525252)
internal val DarkOutline = Color(0xFF404040)
internal val DarkOutlineVariant = Color(0xFF262626)
internal val DarkAccent = Color(0xFFFAFAFA)
internal val DarkOnAccent = Color(0xFF000000)
internal val DarkSuccess = Color(0xFF4ADE80)
internal val DarkOnSuccess = Color(0xFF000000)
internal val DarkWarning = Color(0xFFFBBF24)
internal val DarkOnWarning = Color(0xFF000000)
internal val DarkError = Color(0xFFF87171)
internal val DarkOnError = Color(0xFF000000)
internal val DarkInfo = Color(0xFF60A5FA)
internal val DarkOnInfo = Color(0xFF000000)
internal val DarkScrim = Color(0x8F000000)
