package com.venbiasa.wailo.sdk.android

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import okio.ByteString.Companion.decodeBase64
import okio.ByteString.Companion.toByteString
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The device SDK's persistence seam, kept behind an interface for one reason: the platform pieces
 * ([PrefsKeyValueStore], [SealedKeyValueStore]) are `android.*` and JVM unit tests get stubs that throw,
 * so without it the handshake, host resolution and pairing would be manual-smoke-only — which is
 * exactly how the iOS reconnect bug in ADR-0046 went unnoticed.
 *
 * The default everywhere is [InMemoryKeyValueStore]; [Wailo.attach] swaps in the persistent pair once a
 * `Context` exists.
 */
internal interface WailoKeyValueStore {
    fun get(key: String): String?
    fun put(key: String, value: String?)
    fun keys(): Set<String>
}

internal class InMemoryKeyValueStore : WailoKeyValueStore {
    private val entries = LinkedHashMap<String, String>()

    @Synchronized
    override fun get(key: String): String? = entries[key]

    @Synchronized
    override fun put(key: String, value: String?) {
        if (value == null) entries.remove(key) else entries[key] = value
    }

    @Synchronized
    override fun keys(): Set<String> = entries.keys.toSet()
}

internal class PrefsKeyValueStore(context: Context, name: String) : WailoKeyValueStore {

    private val prefs = context.applicationContext.getSharedPreferences(name, Context.MODE_PRIVATE)

    override fun get(key: String): String? = prefs.getString(key, null)

    override fun put(key: String, value: String?) {
        prefs.edit().apply { if (value == null) remove(key) else putString(key, value) }.apply()
    }

    override fun keys(): Set<String> = prefs.all.keys.toSet()
}

/**
 * Seals every value under an AES-256-GCM key held in the Android Keystore — the counterpart to the iOS
 * Keychain, and for the same reason: a long-term pairing key in a world-readable preferences file would
 * let anything that can read it impersonate this device to the Studio it paired with.
 *
 * A Keystore that refuses (rare, but some vendors' do, and a key does not survive a
 * backup-and-restore) degrades to "nothing was remembered": the value reads back as absent and the
 * device simply re-establishes on first contact. That is a visible degradation, and much better than
 * the alternative of quietly writing the secret in clear.
 */
internal class SealedKeyValueStore(
    private val inner: WailoKeyValueStore,
    private val alias: String,
) : WailoKeyValueStore {

    override fun get(key: String): String? {
        val stored = inner.get(key) ?: return null
        val separator = stored.indexOf(SEPARATOR)
        if (separator <= 0) return null
        val iv = stored.substring(0, separator).decodeBase64()?.toByteArray() ?: return null
        val sealed = stored.substring(separator + 1).decodeBase64()?.toByteArray() ?: return null
        return runCatching {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
            }
            String(cipher.doFinal(sealed))
        }.getOrNull()
    }

    override fun put(key: String, value: String?) {
        if (value == null) {
            inner.put(key, null)
            return
        }
        val encoded = runCatching {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key()) }
            val sealed = cipher.doFinal(value.toByteArray())
            cipher.iv.toByteString().base64() + SEPARATOR + sealed.toByteString().base64()
        }.getOrNull() ?: return
        inner.put(key, encoded)
    }

    override fun keys(): Set<String> = inner.keys()

    // The IV is generated by the cipher, not by us: Keystore keys reject a caller-supplied GCM IV
    // precisely to stop a nonce being reused under one key.
    private fun key(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getKey(alias, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER).apply {
            init(
                KeyGenParameterSpec.Builder(
                    alias,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(KEY_BITS)
                    .build(),
            )
        }.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
        const val KEY_BITS = 256
        const val SEPARATOR = ':'
    }
}
